variables:
  GIT_SUBMODULE_STRATEGY: normal
  DOCKER_IMAGE: ${CI_REGISTRY_IMAGE}

stages:
- build
- deploy

build:
  stage: build
  image:
    name: docker
  script:
  - docker build --build-arg REACT_APP_BRAND=${BRANDING} --tag ${DOCKER_IMAGE}:${CI_COMMIT_BRANCH} .
  tags:
  - docker

deploy:
  stage: deploy
  before_script:
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
  - docker push ${DOCKER_IMAGE}:${CI_COMMIT_BRANCH}
  tags:
  - docker
  dependencies:
  - build

deploy.latest:
  extends: deploy
  variables:
    DOCKER_TAG: latest
  only:
    refs:
    - master